name: "Espressif IoT Development Framework (ESP-IDF)"
description: "This action build your firmware for ESP32 directly in GitHub using Espressif ESP-IDF Docker image."
inputs:
  path:
    description: 'Relative path under $GITHUB_WORKSPACE to place the repository'
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}